stages:
  data_ingestion:
    cmd: python src/Kidney_CTScan/pipeline/stage_01_data_ingestion.py
    deps:
      - src/Kidney_CTScan/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/KidneyCTScan
  
  prepare_base_model:
    cmd: python src/Kidney_CTScan/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/Kidney_CTScan/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model
  
  training:
    cmd: python src/Kidney_CTScan/pipeline/stage_03_model_training.py
    deps:
      - src/Kidney_CTScan/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/KidneyCTScan
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/model_training
  
  evaluation:
    cmd: python src/Kidney_CTScan/pipeline/stage_04_model_evaluation.py
    deps:
      - src/Kidney_CTScan/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/KidneyCTScan
      - artifacts/model_training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: false